import swaggerJSDoc from "swagger-jsdoc";
import swaggerUI from "swagger-ui-express";

const options = {
    definition: {
        openapi: "3.0.0",
        info: {
            title: "Downloader API",
            version: "1.0.0",
            description: "Downloader API with autogenerated swagger doc",
        },
        tags: [
            {
                name: "Video Downloader",
                description: "API endpoints for video downloading operations"
            }
        ]
    },
    apis: ["*/routes/*.js"], // Path to API route files
};

const swaggerSpec = swaggerJSDoc(options);

function setupSwagger(app) {
    app.use("/api-docs", swaggerUI.serve, swaggerUI.setup(swaggerSpec));
}

export default setupSwagger;
